# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b379632f78f1d88f47b08468518bf25c190d05aed1ae61dfc9c5afb31a742ebe52d60d8eedf0a9b2cdeb5fb13a8266d3aa750d31eb18d7d00d383abca0defd

test:
  secret_key_base: a6b5c767250cd534d02bbc421a0ea183e8eddc6563fba2527d23ec76d4766d0c5a02a521ff5159157c838d488606f44d42af17bd0cb21ccef73c25fbe82cc95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
